### ISSUE TITLE
Can't get simple example to load properly

### ISSUE THREAD

**Issue by jdenjun** [kinectron/Three-Kinectron#2]
I've cloned this repository and updated the kinectron ip address in the example, but can't see anything on my live server.
I would like to use kinectron with three.js, is this plugin still being supported?

**Comment by lisajamhoury** [comment]
Three-Kinectron is specifically for RGBD feed from Kinect2, but it hasn't been updated in a few years. You don't need anything special to use Kinectron in three.js. See these examples in the Kinectron repo. [Kinect 2](https://github.com/kinectron/kinectron/tree/master/examples/windows_examples/threejs_examples)  | [Azure](https://github.com/kinectron/kinectron/tree/master/examples/azure_examples/threejs_examples)

**Comment by lisajamhoury** [comment]
I'm closing this issue. Please feel free to reopen if this answer did not resolve the issue.
